package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Gocar generated by hbm2java
 */
@Entity
@Table(name = "Gocar", catalog = "work")
public class Gocar implements java.io.Serializable {

    private Integer cid;
    private User user;
    private String pname;
    private Integer number;
    private Double price;
    private Integer isbuy;

    public Gocar() {
    }

    public Gocar(User user, String pname, Integer number, Double price,
                 Integer isbuy) {
        this.user = user;
        this.pname = pname;
        this.number = number;
        this.price = price;
        this.isbuy = isbuy;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY,generator="tableGenerator")
    @TableGenerator(name="tableGenerator",initialValue=10000,allocationSize = 1)
    @Column(name = "cid", unique = true, nullable = false)
    public Integer getCid() {
        return this.cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uid")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "pname", length = 12)
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    @Column(name = "number")
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    @Column(name = "price", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "isbuy")
    public Integer getIsbuy() {
        return this.isbuy;
    }

    public void setIsbuy(Integer isbuy) {
        this.isbuy = isbuy;
    }

}

