package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.*;

/**
 * Gocar generated by hbm2java
 */
@Entity
@Table(name = "Gocar", catalog = "work")
public class Gocar implements java.io.Serializable {

    private Integer cid;
    private User user;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", length = 10)
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    private Date createtime;

    public Gocar() {
    }

    public Gocar(Integer cid, User user, Date createtime) {
        this.cid = cid;
        this.user = user;
        this.createtime = createtime;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO,generator="tg1")
    @TableGenerator(name="tg1",initialValue=10000,allocationSize = 1)
    @Column(name = "cid", unique = true, nullable = false)
    public Integer getCid() {
        return this.cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    @ManyToOne(cascade = {CascadeType.ALL})
    @JoinColumn(name = "uid",referencedColumnName = "id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


}

