package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", catalog = "work")
public class Product implements java.io.Serializable {

    private Integer pid;
    private String pname;
    private Double price;
    private String imgname;
    private Double discount;
    private Set<Order> orders = new HashSet<Order>();

    @ManyToMany(cascade = {CascadeType.ALL})
    public Set<Order> getOrders() {
        return orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

    public Product(Integer pid, String pname, Double price, String imgname, Double discount, Set<Order> orders) {
        this.pid = pid;
        this.pname = pname;
        this.price = price;
        this.imgname = imgname;
        this.discount = discount;
        this.orders = orders;
    }

    public Product() {
    }

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO,generator="tg3")
    @TableGenerator(name="tg3",initialValue=10000,allocationSize = 1)
    @Column(name = "pid", unique = true, nullable = false)
    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    @Column(name = "pname", length = 20)
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    @Column(name = "price", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "imgname", length = 15)
    public String getImgname() {
        return this.imgname;
    }

    public void setImgname(String imgname) {
        this.imgname = imgname;
    }

    @Column(name = "discount", precision = 22, scale = 0)
    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

}
