package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", catalog = "work")
public class Product implements java.io.Serializable {

    private Integer pid;
    private String pname;
    private Double price;
    private Integer number;
    private String imgname;
    private Double discount;

    public Product() {
    }

    public Product(String pname, Double price, Integer number, String imgname,
                   Double discount) {
        this.pname = pname;
        this.price = price;
        this.number = number;
        this.imgname = imgname;
        this.discount = discount;
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY,generator="tableGenerator")
    @TableGenerator(name="tableGenerator",initialValue=10000,allocationSize = 1)
    @Column(name = "pid", unique = true, nullable = false)
    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    @Column(name = "pname", length = 20)
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    @Column(name = "price", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "number")
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    @Column(name = "imgname", length = 15)
    public String getImgname() {
        return this.imgname;
    }

    public void setImgname(String imgname) {
        this.imgname = imgname;
    }

    @Column(name = "discount", precision = 22, scale = 0)
    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

}
