package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "work")
public class User implements java.io.Serializable {
    private Integer id;
    private String name;
    private String pwd;
    private String email;
    private String address;
    private Date registertime;
    private String phone;
    private String sex;
    private Set<Gocar> gocars = new HashSet<Gocar>(0);
    private Set<Order> orders = new HashSet<Order>(0);

    public User() {

    }

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO,generator="tg4")
    @TableGenerator(name="tg4",initialValue=10000,allocationSize = 1)
    @Column(name = "id",unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 12)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "pwd", length = 6)
    public String getPwd() {
        return this.pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    @Column(name = "email", length = 20)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "address", length = 32)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "registetime", length = 19)
    public Date getRegdate() {
        return this.registertime;
    }

    public void setRegdate(Date regdate) {
        this.registertime = regdate;
    }

    @Column(name = "phone", length = 12)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "sex", length = 2)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
    public Set<Gocar> getGocars() {
        return this.gocars;
    }

    public void setGocars(Set<Gocar> gocars) {
        this.gocars = gocars;
    }

    public User(Integer id, String name, String pwd, String email, String address, Date registertime, String phone, String sex, Set<Gocar> gocars, Set<Order> orders) {
        this.id = id;
        this.name = name;
        this.pwd = pwd;
        this.email = email;
        this.address = address;
        this.registertime = registertime;
        this.phone = phone;
        this.sex = sex;
        this.gocars = gocars;
        this.orders = orders;
    }

    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

}
