package model;

// Generated 2017-7-10 21:43:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "work")
public class User implements java.io.Serializable {
    private Integer id;
    private String name;
    private String pwd;
    private String email;
    private String addr1;
    private String addr2;
    private Date regdate;
    private String phone;
    private String sex;
    private String answer;
    private Set<Gocar> gocars = new HashSet<Gocar>(0);
    private Set<Order> orders = new HashSet<Order>(0);

    public User() {

    }

    public User(String name, String pwd, String email, String addr1,
                String addr2, Date regdate, String phone, String sex,
                String answer, Set<Gocar> gocars, Set<Order> orders) {
        this.name = name;
        this.pwd = pwd;
        this.email = email;
        this.addr1 = addr1;
        this.addr2 = addr2;
        this.regdate = regdate;
        this.phone = phone;
        this.sex = sex;
        this.answer = answer;
        this.gocars = gocars;
        this.orders = orders;
    }


    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY,generator="tableGenerator")
    @TableGenerator(name="tableGenerator",initialValue=10000,allocationSize = 1)
    @Column(name = "id",unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 12)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "pwd", length = 6)
    public String getPwd() {
        return this.pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    @Column(name = "email", length = 12)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "addr1", length = 32)
    public String getAddr1() {
        return this.addr1;
    }

    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    @Column(name = "addr2", length = 32)
    public String getAddr2() {
        return this.addr2;
    }

    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "regdate", length = 10)
    public Date getRegdate() {
        return this.regdate;
    }

    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    @Column(name = "phone", length = 12)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "sex", length = 2)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "answer", length = 20)
    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Gocar> getGocars() {
        return this.gocars;
    }

    public void setGocars(Set<Gocar> gocars) {
        this.gocars = gocars;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

}
